import Foundation
import CryptoKit

/// Verifies GDC-format license serials — a Swift port of
/// gdc-license-system's `license_core.py` (`validate_serial_compact`,
/// the same machine-locked format `license_check.cpp` uses for
/// gdc-resolve-encoder), kept byte-for-byte compatible so codes
/// generated by the existing Python tooling (`sell.py`) work here
/// unchanged, and so every GDC product can keep sharing one signing key,
/// one admin tool, and one sales log (`customers.csv`).
///
/// Format: Base32(dash-grouped) of
/// `[4-byte product hash][8-byte big-endian expiry][4-byte nonce][6-byte machine hash][64-byte Ed25519 signature]`
/// — 22 + 64 = 86 raw bytes. Product hash = SHA-512(product id)[:4].
/// Machine hash = SHA-512(hardware UUID)[:6], or all-zero if the code
/// isn't locked to one Mac (see `MachineID.swift`).
///
/// Verification only ever uses the PUBLIC key — the private key that
/// signs new codes stays on Cristi's machine in `gdc-license-system/`,
/// never in this app.
public enum LicenseCore {
    public struct Payload {
        public let expiresAt: Int64 // unix seconds, 0 = never expires
        public let machineLocked: Bool

        public init(expiresAt: Int64, machineLocked: Bool) {
            self.expiresAt = expiresAt
            self.machineLocked = machineLocked
        }
    }

    public enum ValidationError: Error {
        case malformedCode
        case badSignature
        case wrongProduct
        case wrongMachine
        case expired(Int64)
    }

    /// Base64 of the Ed25519 PUBLIC key from gdc-license-system's
    /// keygen.py (`public_key.txt`). Safe to embed: with asymmetric
    /// crypto, only the never-distributed private key can forge a
    /// signature this validates. Shared by both the client app (to
    /// verify) and, indirectly, the vendor app (whose private key must
    /// match this one — see GDCPluginManagerFurnizor/LicenseGenerator.swift).
    static let publicKeyBase64 = "I1h23MNMRbOhc0ObKJrfa3oFHKA9w+SzbNrroAIy8hs="

    /// Exposed so the vendor app's LicenseGenerator can build the exact
    /// same payload shape when signing new codes.
    public static let payloadSize = 22

    /// Validates a serial the user typed/pasted against `expectedProductID`.
    public static func validate(serial: String, expectedProductID: String) -> Result<Payload, ValidationError> {
        guard let packed = base32Decode(serial), packed.count == payloadSize + 64 else {
            return .failure(.malformedCode)
        }
        let payloadBytes = packed.prefix(payloadSize)
        let signature = packed.suffix(64)

        guard let publicKeyData = Data(base64Encoded: publicKeyBase64),
              let publicKey = try? Curve25519.Signing.PublicKey(rawRepresentation: publicKeyData) else {
            return .failure(.malformedCode)
        }
        guard publicKey.isValidSignature(signature, for: payloadBytes) else {
            return .failure(.badSignature)
        }

        let bytes = Array(payloadBytes)
        let storedProductHash = bytes[0..<4]
        let expectedProductHash = productHash(for: expectedProductID)
        guard Array(storedProductHash) == expectedProductHash else {
            return .failure(.wrongProduct)
        }

        var expiresAt: Int64 = 0
        for i in 4..<12 { expiresAt = (expiresAt << 8) | Int64(bytes[i]) }

        let storedMachineHash = Array(bytes[16..<22])
        let isMachineLocked = storedMachineHash.contains { $0 != 0 }
        if isMachineLocked {
            guard storedMachineHash == MachineID.hashBytes else {
                return .failure(.wrongMachine)
            }
        }

        if expiresAt != 0 && expiresAt < Int64(Date().timeIntervalSince1970) {
            return .failure(.expired(expiresAt))
        }
        return .success(Payload(expiresAt: expiresAt, machineLocked: isMachineLocked))
    }

    /// Exposed so the vendor app's LicenseGenerator computes the exact
    /// same product hash when signing a new code for a given product ID.
    public static func productHash(for productID: String) -> [UInt8] {
        Array(SHA512.hash(data: Data(productID.utf8)).prefix(4))
    }

    // MARK: - Base32 (RFC 4648, matching Python's base64.b32encode/decode)

    private static let base32Alphabet = Array("ABCDEFGHIJKLMNOPQRSTUVWXYZ234567")

    public static func base32Encode(_ data: Data) -> String {
        var bits = 0, value = 0
        var output = ""
        for byte in data {
            value = (value << 8) | Int(byte)
            bits += 8
            while bits >= 5 {
                output.append(base32Alphabet[(value >> (bits - 5)) & 0x1F])
                bits -= 5
            }
        }
        if bits > 0 {
            output.append(base32Alphabet[(value << (5 - bits)) & 0x1F])
        }
        return output
    }

    /// Exposed so the vendor app's LicenseGenerator can decode a pasted
    /// machine-ID string into the 6 raw bytes it needs to embed.
    public static func base32Decode(_ string: String) -> Data? {
        let cleaned = string.uppercased()
            .replacingOccurrences(of: "-", with: "")
            .replacingOccurrences(of: " ", with: "")
            .replacingOccurrences(of: "=", with: "")
        var bits = 0, value = 0
        var output = [UInt8]()
        for char in cleaned {
            guard let index = base32Alphabet.firstIndex(of: char) else { return nil }
            value = (value << 5) | index
            bits += 5
            if bits >= 8 {
                output.append(UInt8((value >> (bits - 8)) & 0xFF))
                bits -= 8
            }
        }
        return Data(output)
    }
}
